# Generated by Django 5.2.9 on 2025-12-10 10:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactpage_from_address_contactpage_subject_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesseursPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Nos professeurs', max_length=150, verbose_name='Titre principal')),
                ('intro_subtitle', models.TextField(blank=True, default='Voici un exemple de section professeurs que vous pouvez adapter.', help_text="Ex : 'Voici un exemple de section professeurs...'", verbose_name='Texte d’intro')),
                ('professeurs', wagtail.fields.StreamField([('professeurs', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du service', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant le service (format horizontal de préférence).', 'label': 'Image du service', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5)]], {})}, help_text='Liste complète des professeurs.', verbose_name='Professeurs')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
