# Generated by Django 5.2.9 on 2025-12-12 10:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_professeurspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeurspage',
            name='professeurs',
            field=wagtail.fields.StreamField([('professeur', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre du service', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant le service (format horizontal de préférence).', 'label': 'Image du service', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5)]], {})}, help_text='Liste complète des professeurs.', verbose_name='Professeurs'),
        ),
    ]
