# Generated by Django 5.2.9 on 2025-12-15 08:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_professeurspage_professeurs'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(default='Nos destinations', max_length=150, verbose_name='Titre principal')),
                ('intro_subtitle', models.TextField(blank=True, default='Voici un exemple de section destinations que vous pouvez adapter.', help_text="Ex : 'Voici un exemple de section destinations...'", verbose_name='Texte d’intro')),
                ('destinations', wagtail.fields.StreamField([('destination', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre de la destination', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant la destination (format horizontal de préférence).', 'label': 'Image de la destination', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5)]], {})}, help_text='Liste complète des destinations proposés.', verbose_name='Destinations')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_preview',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_preview_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_preview_title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='destinations_preview',
            field=wagtail.fields.StreamField([('destination', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Petit texte au-dessus (ex : 01, 02, 03...)', 'label': 'Badge / numéro', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titre de la destination', 'max_length': 120, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Description courte', 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image ou icône illustrant la destination (format horizontal de préférence).', 'label': 'Image de la destination', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Point clé'}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Liste de points clés (bullet points)', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('badge', 0), ('title', 1), ('description', 2), ('image', 3), ('features', 5)]], {})}, verbose_name='Destinations à afficher sur l’accueil (aperçu)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='destinations_preview_intro',
            field=models.TextField(blank=True, default='Un aperçu rapide de nos destinations.', help_text='Petite phrase pour introduire les destinations.', verbose_name='Texte d’intro de la section destinations (accueil)'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='destinations_preview_title',
            field=models.CharField(default='Nos destinations', max_length=150, verbose_name='Titre de la section destinations (accueil)'),
        ),
        migrations.DeleteModel(
            name='ProfesseursPage',
        ),
        migrations.DeleteModel(
            name='ServicesPage',
        ),
    ]
