# Generated by Django 5.2.9 on 2025-12-15 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_destinationspage_remove_servicespage_page_ptr_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image 4'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image_caption',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Légende des images'),
        ),
    ]
